"""NN parameters"""

__all__ = ['LOOKBACK', 'INPUT_DIM', 'HIDDEN_DIM', 'OUTPUT_DIM', 'NUM_LAYERS', 'lstm', 'LEARNING_RATE', 'BATCH_SIZE']

INPUT_DIM = 14
HIDDEN_DIM = 32
NUM_LAYERS = 1
OUTPUT_DIM = 1
NUM_EPOCHS = 100
LOOKBACK = 5
BATCH_SIZE = 64

LEARNING_RATE = 0.0008
